version: '3.8'
services:

  # Qualitative-Indicators-API
  i4n-middleware-api:
    container_name: i4n-middleware-api
    image: 237944624957.dkr.ecr.eu-south-1.amazonaws.com/i4n-middleware-api:latest
    ports:
      - "8080:8080"
    environment:
      idm.auth-server-url: "https://idm.digital-enabler.eng.it/auth"
      idm.realm: "invest4nature"
      idm.client-id: "middleware-app"
      idm.client-secret: ""
      etcd.enabled: "false"
      application.frontend-url: "http://localhost:3000"
      application.backend-url: "http://localhost:8080"
      microservices.recommender-url: "http://recommender-backend:8000"
      microservices.cost-benefit-url: "http://cost-benefit-backend:8000"
      microservices.qualitative-indicators-url: "http://qualitativeindicators-backend:8000"
    networks:
      - invest4nature

  # MICROSERVICES

  # cost-benefit-API
  cost-benefit-backend-api:
    container_name: cost-benefit-backend
    image: 237944624957.dkr.ecr.eu-south-1.amazonaws.com/cost-benefit-backend:latest
    ports:
      - "8000:8000"
    environment:
      SAVELOG: True
      LOGLEVEL: INFO
      LOGMODE: a
      LOGPATH: /my_optimizer_server_log.log
      SAVEFILES: True
    networks:
      - invest4nature

  # Recommender-API
  recommender-backend-api:
    container_name: recommender-backend
    image: 237944624957.dkr.ecr.eu-south-1.amazonaws.com/recommender-backend:latest
    ports:
      - "8003:8000"
    environment:
      SAVELOG: True
      LOGLEVEL: INFO
      LOGMODE: a
      LOGPATH: /my_rs_server_log.log
      SAVEFILES: True
      DEFAULT_EMBEDDING_MODEL: sentence-transformers/all-mpnet-base-v2
      DEFAULT_RERANK_MODEL: cross-encoder/ms-marco-MiniLM-L-6-v2
      VECTOR_DB_PERSISTENCE_PATH: persistence/I4N
      VECTOR_DB_COLLECTION_NAME: I4N_oppla
    networks:
      - invest4nature

  # Qualitative-Indicators-API
  qualitativeindicators-backend-api:
    container_name: qualitativeindicators-backend
    image: 237944624957.dkr.ecr.eu-south-1.amazonaws.com/qualitativeindicators-backend
    ports:
      - "8008:8000"
    environment:
      SAVELOG: True
      LOGLEVEL: INFO
      LOGMODE: a
      LOGPATH: /my_qi_server_log.log
      SAVEFILES: True
      DEFAULT_EMBEDDING_MODEL: sentence-transformers/all-mpnet-base-v2
      NBS_EMBEDDINGS_PATH: persistence/category_embeddings_mpnet
      INDICATORS_MAP_PATH: persistence/nbs_with_services.json
    networks:
      - invest4nature

networks:
  invest4nature:
    driver: bridge